# Goal: create deployment to create pods for posts service.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1 # number of pods we want to create that running certain image
  selector: # which pods that we want to replicate & manage
    matchLabels:
      app: posts
  template: # specify the configuration of the pod
    metadata: # the metadata for the selector matchLabels
      labels:
        app: posts
    spec: # the image we want to run inside the container inside the pods
      containers:
        - name: posts
          image: dodyvirgiawan/posts:latest

---
# Goal: Create a Cluster IP Service for posts microservice (expose to other pods)
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports: 
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
